DROP MATERIALIZED VIEW IF EXISTS public.mv_search_analytics_summary_30_days CASCADE;
DROP TABLE IF EXISTS public.job_applications CASCADE;
DROP TABLE IF EXISTS public.developer_permissions CASCADE;
DROP TABLE IF EXISTS public.job_tags CASCADE;
DROP TABLE IF EXISTS public.tags CASCADE;
DROP TABLE IF EXISTS public.jobs CASCADE;
DROP TABLE IF EXISTS public.developers CASCADE;
DROP TABLE IF EXISTS public.companies CASCADE;
DROP TABLE IF EXISTS public.search_analytics_events CASCADE;


CREATE TABLE IF NOT EXISTS public.companies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug CHARACTER VARYING(100) NOT NULL,
    name CHARACTER VARYING(255) NOT NULL,
    website CHARACTER VARYING(255),
    logo_url TEXT,
    total_jobs INTEGER DEFAULT 0,
    avg_salary_all NUMERIC DEFAULT 0 NOT NULL,
    salary_count_all INTEGER DEFAULT 0 NOT NULL,
    clicks INTEGER DEFAULT 0,
    views INTEGER DEFAULT 0,
    views_7d INTEGER DEFAULT 0,
    api_key CHARACTER VARYING(255)
    );

CREATE TABLE IF NOT EXISTS public.developers (
    id UUID NOT NULL PRIMARY KEY,
    name CHARACTER VARYING(255) NOT NULL,
    email CHARACTER VARYING(255) NOT NULL,
    api_key CHARACTER VARYING(255) NOT NULL,
    rate_limit_per_hour INTEGER DEFAULT 100 NOT NULL,
    is_active BOOLEAN DEFAULT TRUE NOT NULL,
    tier CHARACTER VARYING(50) DEFAULT 'free'::character varying NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS public.developer_permissions (
    developer_id UUID NOT NULL,
    permission VARCHAR(100) NOT NULL,
    CONSTRAINT fk_developer_permissions FOREIGN KEY (developer_id) REFERENCES public.developers(id) ON DELETE CASCADE,
    PRIMARY KEY (developer_id, permission)
);

CREATE TABLE IF NOT EXISTS public.jobs (
    id UUID NOT NULL PRIMARY KEY,
    company_id BIGINT,
    title CHARACTER VARYING(255) NOT NULL,
    slug CHARACTER VARYING(255) NOT NULL,
    description TEXT,
    salary_min NUMERIC,
    salary_max NUMERIC,
    location CHARACTER VARYING(255),
    workplace CHARACTER VARYING(50),
    job_type CHARACTER VARYING(50),
    experience_level CHARACTER VARYING(50),
    apply_url TEXT,
    is_featured BOOLEAN DEFAULT FALSE,
    is_sticky BOOLEAN DEFAULT FALSE,
    status CHARACTER VARYING(20),
    quality_score INTEGER,
    url TEXT,
    published_at TIMESTAMP WITHOUT TIME ZONE,
    expires_at TIMESTAMP WITHOUT TIME ZONE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_jobs_company FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS public.job_applications (
        id UUID PRIMARY KEY,
        job_id UUID NOT NULL,
        developer_id UUID NOT NULL,
        cover_letter TEXT,
        experience_years INT,
        github_url VARCHAR(255),
        applied_at TIMESTAMP WITH TIME ZONE NOT NULL,
        CONSTRAINT fk_application_job FOREIGN KEY (job_id) REFERENCES public.jobs(id) ON DELETE CASCADE,
        CONSTRAINT fk_application_developer FOREIGN KEY (developer_id) REFERENCES public.developers(id) ON DELETE CASCADE
    );

CREATE TABLE IF NOT EXISTS public.tags (
        tag_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name CHARACTER VARYING(100) NOT NULL,
        job_count INTEGER DEFAULT 0
    );

CREATE TABLE IF NOT EXISTS public.job_tags (
        job_id UUID NOT NULL,
        tag_id INTEGER NOT NULL,
        CONSTRAINT fk_job_tags_job FOREIGN KEY (job_id) REFERENCES public.jobs(id) ON DELETE CASCADE,
        CONSTRAINT fk_job_tags_tag FOREIGN KEY (tag_id) REFERENCES public.tags(tag_id) ON DELETE CASCADE,
        PRIMARY KEY (job_id, tag_id)
    );

CREATE TABLE IF NOT EXISTS public.search_analytics_events (
        id UUID NOT NULL PRIMARY KEY,
        endpoint CHARACTER VARYING(50),
        search_query CHARACTER VARYING(255),
        tags TEXT[],
        user_agent CHARACTER VARYING(512),
        results_count INTEGER,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
    );

CREATE UNIQUE INDEX IF NOT EXISTS idx_companies_slug ON public.companies(slug);
CREATE UNIQUE INDEX IF NOT EXISTS idx_jobs_slug ON public.jobs(slug);
CREATE UNIQUE INDEX IF NOT EXISTS idx_developers_email ON public.developers(email);
CREATE UNIQUE INDEX IF NOT EXISTS idx_tags_name ON public.tags(name);

CREATE INDEX IF NOT EXISTS idx_job_tags_tag_id ON public.job_tags(tag_id);

CREATE MATERIALIZED VIEW IF NOT EXISTS public.mv_search_analytics_summary_30_days AS
WITH summary_metrics AS (
    SELECT
        'endpoint' AS metric_type,
        endpoint AS metric_key,
        COUNT(*) AS metric_count,
        ROUND(AVG(results_count)) AS avg_results,
        0::BIGINT AS zero_result_searches
    FROM public.search_analytics_events
    WHERE created_at >= NOW() - INTERVAL '30 days' AND endpoint IS NOT NULL
    GROUP BY endpoint

    UNION ALL

    SELECT
        'query' AS metric_type,
        search_query AS metric_key,
        COUNT(*) AS metric_count,
        ROUND(AVG(results_count)) AS avg_results,
        0::BIGINT AS zero_result_searches
    FROM public.search_analytics_events
    WHERE created_at >= NOW() - INTERVAL '30 days' AND search_query IS NOT NULL
    GROUP BY search_query

    UNION ALL

    SELECT
        'tag' AS metric_type,
        UNNEST(tags) AS metric_key,
        COUNT(*) AS metric_count,
        0::BIGINT AS avg_results,
        0::BIGINT AS zero_result_searches
    FROM public.search_analytics_events
    WHERE created_at >= NOW() - INTERVAL '30 days' AND tags IS NOT NULL
    GROUP BY metric_key

    UNION ALL

    SELECT
        'counter' AS metric_type,
        'global' AS metric_key,
        COUNT(*) AS metric_count,
        0::BIGINT AS avg_results,
        COUNT(*) FILTER (WHERE results_count = 0) AS zero_result_searches
    FROM public.search_analytics_events
    WHERE created_at >= NOW() - INTERVAL '30 days'
)
SELECT * FROM summary_metrics;

CREATE UNIQUE INDEX IF NOT EXISTS idx_mv_search_summary_unique
    ON public.mv_search_analytics_summary_30_days (metric_type, metric_key);

CREATE INDEX IF NOT EXISTS idx_jobs_company_id ON public.jobs(company_id);
CREATE INDEX IF NOT EXISTS idx_job_applications_job_id ON public.job_applications(job_id);
CREATE INDEX IF NOT EXISTS idx_job_applications_developer_id ON public.job_applications(developer_id);

CREATE INDEX IF NOT EXISTS idx_search_analytics_events_created_at ON public.search_analytics_events(created_at);

CREATE OR REPLACE FUNCTION public.update_company_stats_incremental()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
DECLARE
old_slug VARCHAR(100);
    new_slug VARCHAR(100);
BEGIN
    IF (TG_OP = 'INSERT' OR TG_OP = 'UPDATE') THEN
SELECT slug INTO new_slug FROM public.companies WHERE id = NEW.company_id;
END IF;

    IF (TG_OP = 'DELETE' OR TG_OP = 'UPDATE') THEN
SELECT slug INTO old_slug FROM public.companies WHERE id = OLD.company_id;
END IF;

--     INSERT
    IF (TG_OP = 'INSERT') THEN
        IF new_slug IS NOT NULL THEN
UPDATE public.companies SET
        total_jobs = total_jobs + 1,
        avg_salary_all = CASE
            WHEN salary_count_all = 0 THEN ((COALESCE(NEW.salary_min, 0) + COALESCE(NEW.salary_max, 0)) / 2)
             ELSE ((avg_salary_all * salary_count_all) + ((COALESCE(NEW.salary_min, 0) + COALESCE(NEW.salary_max, 0)) / 2)) / (salary_count_all + 1)
                END,
        salary_count_all = salary_count_all + 1
WHERE slug = new_slug;
END IF;

    -- DELETE
    ELSIF (TG_OP = 'DELETE') THEN
        IF old_slug IS NOT NULL THEN
UPDATE public.companies SET
        total_jobs = CASE WHEN total_jobs > 0 THEN total_jobs - 1 ELSE 0 END,
        avg_salary_all = CASE
        WHEN salary_count_all > 1 THEN
        COALESCE(((avg_salary_all * salary_count_all) - ((COALESCE(OLD.salary_min, 0) + COALESCE(OLD.salary_max, 0)) / 2)) / (salary_count_all - 1), 0)
        ELSE 0
        END,
    salary_count_all = CASE WHEN salary_count_all > 0 THEN salary_count_all - 1 ELSE 0 END
WHERE slug = old_slug;
END IF;

    -- UPDATE
    ELSIF (TG_OP = 'UPDATE') THEN
        -- The job moved to a completely different company
        IF (COALESCE(NEW.company_id, 0) != COALESCE(OLD.company_id, 0)) THEN
            -- Remove from old company
            IF old_slug IS NOT NULL THEN
            UPDATE public.companies SET
                        total_jobs = CASE WHEN total_jobs > 0 THEN total_jobs - 1 ELSE 0 END,
                         avg_salary_all = CASE
                             WHEN salary_count_all > 1 THEN
                            COALESCE(((avg_salary_all * salary_count_all) - ((COALESCE(OLD.salary_min, 0) + COALESCE(OLD.salary_max, 0)) / 2)) / (salary_count_all - 1), 0)
                                ELSE 0
                                END,
                        salary_count_all = CASE WHEN salary_count_all > 0 THEN salary_count_all - 1 ELSE 0 END
WHERE slug = old_slug;
END IF;

            -- Add to new company
            IF new_slug IS NOT NULL THEN
            UPDATE public.companies SET
                    total_jobs = total_jobs + 1,
                    avg_salary_all = CASE
                        WHEN salary_count_all = 0 THEN ((COALESCE(NEW.salary_min, 0) + COALESCE(NEW.salary_max, 0)) / 2)
                        ELSE ((avg_salary_all * salary_count_all) + ((COALESCE(NEW.salary_min, 0) + COALESCE(NEW.salary_max, 0)) / 2)) / (salary_count_all + 1)
                            END,
                    salary_count_all = salary_count_all + 1
WHERE slug = new_slug;
END IF;
        -- Same company, but the salary numbers changed
        ELSIF (COALESCE(NEW.salary_min, 0) != COALESCE(OLD.salary_min, 0) OR COALESCE(NEW.salary_max, 0) != COALESCE(OLD.salary_max, 0)) THEN
            IF new_slug IS NOT NULL THEN
UPDATE public.companies SET
    avg_salary_all = CASE
             WHEN public.companies.salary_count_all <= 1 THEN
                ((COALESCE(NEW.salary_min, 0) + COALESCE(NEW.salary_max, 0)) / 2)
                ELSE
                    ((public.companies.avg_salary_all * public.companies.salary_count_all)
                            - ((COALESCE(OLD.salary_min, 0) + COALESCE(OLD.salary_max, 0)) / 2)
                            + ((COALESCE(NEW.salary_min, 0) + COALESCE(NEW.salary_max, 0)) / 2))
                             / public.companies.salary_count_all
        END
WHERE slug = new_slug;
END IF;
END IF;
END IF;

RETURN NEW;
END;
$function$;

CREATE TRIGGER trigger_update_company_stats_incremental
    AFTER INSERT OR
UPDATE OR
DELETE
ON public.jobs
    FOR EACH ROW
    EXECUTE FUNCTION public.update_company_stats_incremental();

INSERT INTO public.search_analytics_events (id, endpoint, search_query, tags, user_agent, results_count, created_at)
VALUES
    (gen_random_uuid(), '/api/v1/jobs/search', 'kotlin developer', ARRAY['kotlin', 'backend', 'spring'], 'Mozilla/5.0', 12, NOW() - INTERVAL '2 hours'),
    (gen_random_uuid(), '/api/v1/jobs/search', 'react developer', ARRAY['react', 'frontend'], 'Mozilla/5.0', 25, NOW() - INTERVAL '1 day'),
    (gen_random_uuid(), '/api/v1/jobs/search', 'rust engineer', ARRAY['rust', 'systems'], 'Mozilla/5.0', 0, NOW() - INTERVAL '3 days'),
    (gen_random_uuid(), '/api/v1/companies/search', 'EPAM', ARRAY['corporate', 'outsource'], 'Mozilla/5.0', 3, NOW() - INTERVAL '5 days'),
    (gen_random_uuid(), '/api/v1/jobs/search', 'kotlin developer', ARRAY['kotlin'], 'Mozilla/5.0', 15, NOW() - INTERVAL '15 mins'),
    (gen_random_uuid(), '/api/v1/jobs/search', 'kotlin developer', ARRAY['kotlin', 'aws'], 'Mozilla/5.0', 8, NOW() - INTERVAL '40 mins'),
    (gen_random_uuid(), '/api/v1/jobs/search', 'manager', ARRAY['management'], 'Mozilla/5.0', 0, NOW() - INTERVAL '6 days')
    ON CONFLICT DO NOTHING;

REFRESH MATERIALIZED VIEW public.mv_search_analytics_summary_30_days;

